### ISSUE TITLE
docker部署，login界面输入框无反应

### ISSUE THREAD

**Issue by nn200433** [team-ide/teamide#121]
```yaml
version: '3'
services:
  rabbit:
    image: teamide/teamide-server:latest
    container_name: teamide
    restart: unless-stopped
    ports:
      - 21080:21080
    volumes:
      - ./data:/opt/teamide/data
```

这个试了好多浏览器，搜狗/chrome/firefox/edge 都一样
